package cardJitsu;

public enum EfektuMota {
	BIGEHITU,//2
	BIKENDU,//3
	ZENBAKIALDAKETA,//1
	KENDUSUA,//6
	KENDUURA,//5
	KENDUELURRA,//4
	KENDUGORRIBAT,//7
	KENDUURDINBAT,//8
	KENDUHORIBAT,//10
	KENDUBERDEBAT,//9
	KENDULARANJABAT,//11
	KENDUMOREBAT,//12
	KENDUGORRIGUZTIAK,//19
	KENDUURDINGUZTIAK,//20
	KENDUHORIGUZTIAK,//21
	KENDUBERDEGUZTIAK,//22
	KENDULARANJAGUZTIAK,//23
	KENDUMOREGUZTIAK,//24
	SUTIKELURRARA,//18
	ELURRATIKURARA,//17
	URATIKSURA,//16
	SUABLOKEATU,//14
	URABLOKEATU,//15
	ELURRABLOKEATU//13
}
