package CardJitsu;

public enum EfektuMota {
	BIGEHITU,
	BIKENDU,
	ZENBAKIALDAKETA,
	KENDUSUA,
	KENDUURA,
	KENDUELURRA,
	KENDUGORRIBAT,
	KENDUURDINBAT,
	KENDUHORIBAT,
	KENDUBERDEBAT,
	KENDULARANJABAT,
	KENDUMOREBAT,
	KENDUGORRIGUZTIAK,
	KENDUURDINGUZTIAK,
	KENDUHORIGUZTIAK,
	KENDUBERDEGUZTIAK,
	KENDULARANJAGUZTIAK,
	KENDUMOREGUZTIAK,
	SUTIKELURRARA,
	ELURRATIKURARA,
	URATIKSURA,
	SUABLOKEATU,
	URABLOKEATU,
	ELURRABLOKEATU
}
